board/urls.py
from django.urls import path
from . import views
from .views import AnnouncementCreate, PostList, PostDetail, PostCategory, AnnouncementUpdate, CommentCreate, \
    CommentList, CommentDetail, accept_comment, deny_comment

app_name = 'board'

urlpatterns = [
    path('', PostList.as_view(), name='announcement_list'),
    path('<int:pk>/', PostDetail.as_view(), name='announcement_detail'),
    path('add/', AnnouncementCreate.as_view(), name='ann_create'),
    path('<int:pk>/update/', AnnouncementUpdate.as_view(), name='ann_update'),
    path('category/<int:pk>/', PostCategory.as_view(), name='category'),
    path('<int:pk>/comment/', CommentCreate.as_view(), name="comment"),
    path('comments/', CommentList.as_view(), name="comment_list"),
    path('comments/<int:pk>/', CommentDetail.as_view(), name="comment_detail"),
    path('comments/<int:pk>/accept/', accept_comment, name="accept"),
    path('comments/<int:pk>/deny/', deny_comment, name="deny"),
    path('success/', views.SuccessView.as_view(), name="success"),
]

bulletinboard/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from bulletinboard import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('board.urls',
                     namespace='board')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

board/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Announcement(models.Model):
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='person')
    text = models.TextField()
    image = models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')
    url = models.URLField(blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, verbose_name='Категория',
                                 related_name='cats')

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:announcement_detail',
                       args=[str(self.id)])


class Comment(models.Model):
    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name='Имя')
    email = models.EmailField()
    text = models.TextField(verbose_name="Отклик")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [models.Index(fields=['-created'])]

    def __str__(self):
        return f"Отклик от {self.name} к {self.announcement}"


class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('board:category', args=[self.id])

board/forms.py
from django.core.exceptions import ValidationError

from board.models import Announcement, Comment
from django import forms


class AddAnnouncementForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Announcement
        fields = ['title', 'text', 'image', 'category', 'url']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 200:
            raise ValidationError('Длина превышает 200 символов')

        return title


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'text',
        ]
        labels = {
            'Введите ваше сообщение : '
        }

board/views.py
import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.context_processors import request
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, TemplateView

from board.forms import AddAnnouncementForm, CommentCreateForm
from board.models import Announcement, Category, Comment
from board.tasks import ann_created
from board.utils import DataMixin
from django.contrib import messages


class PostList(ListView):
    model = Announcement
    template_name = 'announcement/list.html'
    context_object_name = 'announcements'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class PostCategory(DataMixin, ListView):
    model = Announcement
    template_name = 'announcement/list.html'
    context_object_name = 'announcements'
    paginate_by = 4

    def get_queryset(self):
        """
        Убираем два лишних запроса к БД за счет select_related.
        """
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Announcement.objects.filter(category=self.category).select_related('category')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class PostDetail(DetailView):
    model = Announcement
    template_name = 'announcement/detail.html'

    def get_success_url(self):
        return reverse('announcement_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.object.category
        context['announcement'] = Announcement.objects.get(pk=self.kwargs['pk'])
        context['comments'] = Comment.objects.filter(announcement=context['announcement'], active=True)
        return context


class AnnouncementCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Создание нового объявления.
    """
    permission_required = 'news.add_post'
    form_class = AddAnnouncementForm
    model = Announcement
    template_name = 'announcement/announcement_create.html'

    def form_valid(self, form):
        """
        ann_created - таска на отправку уведомления всем зарегистрированным пользователям о создании нового объявления.
        """
        post = form.save(commit=False)
        if self.request.method == 'POST':
            post.author, created = User.objects.get_or_create(id=self.request.user.id)
            post.save()
            messages.success(self.request, 'Объявление успешно создано')
        else:
            messages.error(self.request, 'Произошла ошибка, пожалуйста повторите действие или обратитесь к администратору')
            ann_created(announcement_id=post.id)
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AnnouncementUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Announcement
    form_class = AddAnnouncementForm
    template_name = 'announcement/announcement_update.html'
    context_object_name = 'announcement'
    success_message = "Объявление отредактировано успешно!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_template_names(self):
        """
        Если зарегистрированный пользователь является автором - позволяем редактирование объявления, иначе - статус 403.
        """
        post = self.get_object()
        if post.author == self.request.user:
            self.template_name = 'announcement/announcement_update.html'
            return self.template_name
        else:
            raise PermissionDenied


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'announcement/comment_create.html'
    form_class = CommentCreateForm
    success_url = '/success/'

    def form_valid(self, form):
        """
        Создаем отклик и отправляем автору объявления письмо о новом отклике.
        """
        self.object = form.save(commit=False)
        self.object.user = User.objects.get(id=self.request.user.id)
        self.object.announcement = Announcement.objects.get(id=self.kwargs['pk'])
        self.object.save()
        result = super().form_valid(form)
        send_mail(
            subject=f'Получен отклик по объявлению "{self.object.announcement.title}"',
            message=f'Получен новый отклик по вашему объявлению: "{self.object.text}"',
            from_email=os.getenv('DEFAULT_FROM_EMAIL'),
            recipient_list=[self.object.announcement.author.email]
        )
        messages.success(self.request, 'Ваш отклик успешно отправлен!')
        return result


class CommentDetail(LoginRequiredMixin, DetailView):
    model = Comment

    def get_template_names(self):
        response = self.get_object()
        if response.announcement.author == self.request.user:
            self.template_name = 'announcement/comment_detail.html'
            return self.template_name
        else:
            raise PermissionDenied


class CommentList(LoginRequiredMixin, ListView):
    model = Comment
    template_name = 'announcement/comment_list.html'
    context_object_name = 'comment_list'
    ordering = '-created'

    def get_queryset(self):
        queryset = Comment.objects.filter(announcement__author=self.request.user)
        return queryset


class SuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'announcement/success.html'


@login_required()
def accept_comment(request, pk):
    """
    Отправляем пользователю уведомление по почте, чот его отклик принят.
    """
    comment = Comment.objects.get(pk=pk)
    comment.active = True
    recipient_email = comment.announcement.author.email
    comment.save()
    send_mail(
        subject=f'Доска объявлений: отклик принят',
        message=f'Ваш отклик на пост "{comment.announcement.title}" принят',
        from_email=os.getenv('DEFAULT_FROM_EMAIL'),
        recipient_list=[recipient_email]
    )
    messages.success(request, 'Отклик принят!')
    return HttpResponseRedirect(reverse('board:comment_list'))


@login_required()
def deny_comment(request, pk):
    """
    При нажатии кнопки 'отклонить' - убираем отображение отклика со страницы с объявлением.
    Реализовано вместо функции удаления, чтобы оставлять отклики в БД, просто меняя их статус.
    """
    comment = Comment.objects.get(pk=pk)
    comment.active = False
    comment.save()
    messages.success(request, 'Отклик отклонен!')
    return HttpResponseRedirect(reverse('board:comment_list'))

board/templates/announcement/announcement_create.html
{% load static %}
<!DOCTYPE html> <html>
<head>
<title>
    {% block title %}
    {% endblock %}
</title>
<link href="{% static "styleforms.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
      <a href="{% url "board:announcement_list" %}" class="logo">Announcements</a>
      <ul class="menu">
{% if request.user.is_authenticated %}
    <a href="{% url 'board:ann_create' %}">Разместить объявление</a>
    <a href="{% url 'account_logout' %}">Выйти</a>
{% else %}
    <a href="{% url 'account_login' %}" >Вход</a>   <a href="{% url 'account_signup' %}" >Регистрация</a>
{% endif %}
      </ul>
    </div>
    {% block content %}
<h1>Создайте новое объявление:</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать" />
</form>
{% endblock content %}

board/templates/announcement/announcement_update.html
{% extends 'announcement/announcement_create.html' %}
{% load static %}

{% block title %}
Edit Post
{% endblock title %}

{% block content %}

<h1>Редактировать свое объявление:</h1>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Редактировать" />
</form>
<br>
<br>
{% endblock content %}

board/templates/announcement/comment_create.html
{% extends 'default.html' %}

{% block title %}
<h1>Откликнуться на пост</h1>
<hr>
{% endblock title %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить"/>
    <input type="hidden" name="next" value="{{next}}" />
</form>
{% endblock content %}

board/templates/announcement/comment_detail.html
{% extends 'default.html' %}

{% block content %}
{{ comment.created|date:'d.m.y' }}
<hr>
{{ comment.text }}
<hr>
Отправил: {{ comment.user }}<br>
{% if comment.status == False or comment.status is None %}
    {% if comment.status == True %}
        <p>{{ comment.text }}</p>
    {% else %}
        <a href="{% url 'board:accept' pk=comment.announcement.pk %}"><button>Принять</button></a>
        <a href="{% url 'board:deny' pk=comment.announcement.pk %}"><button>Отклонить</button></a>
    {% endif %}
{% endif %}
{% endblock content %}

board/templates/announcement/comment_list.html
{% extends 'default.html' %}

{% block content %}
{% if comment_list %}
    {% for c in comment_list %}
        {% if c.status == True or c.status is None %}
            <p>{{ c.created|date:'d.m.y' }}</p>
            <p>{{ c.text }}</p>
            <p>Отклик на "{{ c.announcement.title }}" от пользователя {{ c.user }}</p>
                {% if c.status == True %}
                    <p>{{ c.text }}</p>
                {% else %}
                    <a href="{% url 'board:accept' pk=c.pk %}"><input type="submit" value="Принять" />
                    <a href="{% url 'board:deny' pk=c.pk %}"><input type="reset" value="Отклонить" />
                {% endif %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    Откликов нет
{% endif %}
{% endblock content %}

board/templates/announcement/detail.html
{% extends "default.html" %}

{% block title %}
    {{ announcement.title }}
{% endblock %}

{% block content %}
  <h1>{{ announcement.title }}</h1>
      {% if announcement.image %}
    <p><img src="{{ announcement.image.url }}"></p>
{% endif %}
  {{ announcement.text }}
    <p><a href="{% url 'board:ann_update' pk=announcement.pk %}"><input type="submit" value="Редактировать" /></a></p>
    <p><a href="{% url 'board:comment' pk=announcement.pk %}"><input type="submit" value="Отправить отклик" /></a></p>
{% for comment in comments %}
    <div class="comment">
      <p class="info">
        Отклик от {{ comment.announcement.author }}
        Добавлен {{ comment.created }}
      </p>
      {{ comment.text|linebreaks }}
    </div>
{% endfor %}
{% endblock %}

board/templates/announcement/list.html
{% extends "default.html" %}


{% block title %}

{% endblock %}

{% block content %}
{% for announcement in announcements %}
    <h2>
      <a href="{{ announcement.get_absolute_url }}">
        {{ announcement.title }}
      </a>
     <p class="date">
    Опубликовано {{ announcement.publish }} пользователем {{ announcement.author }}</p>
    <p class="date">
    Категория {{ announcement.category }}
     </p>
  {% if announcement.image %}
    <p><img src="{{ announcement.image.url }}"></p>
{% endif %}
        <p>
    {{ announcement.text|truncatewords:20 }}
            </p>
    </h2>
    <hr>
    {% endfor %}
       {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock %}

board/templates/announcement/success.html
{% extends 'default.html' %}

{% block content %}

{% endblock content %}